apiVersion: v1
kind: Secret
metadata:
  name: condor02-postgres-cluster-logical-backup
  namespace: condor-prod
type: Opaque
stringData:
  LOGICAL_BACKUP_S3_BUCKET: REPLACE_ME
  LOGICAL_BACKUP_S3_ENDPOINT: REPLACE_ME
  AWS_ACCESS_KEY_ID: REPLACE_ME
  AWS_SECRET_ACCESS_KEY: REPLACE_ME
  LOGICAL_BACKUP_S3_RETENTION_DAYS: "90"
