apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: condor02-condordatastoreprod
  namespace: condor-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: condor02-postgres-cluster
  name: condordatastoreprod
  owner: condor
