apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: condor-prod
resources:
  - cluster.yaml
  - database-condordatastoreprod.yaml
  - database-keycloak.yaml
  - scheduled-backup-physical.yaml
  - logical-backup-cronjob.yaml
labels:
  - pairs:
      tenant: condor
      app.kubernetes.io/part-of: condor02-postgres-cluster
    includeSelectors: false
