apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: condor02-postgres-cluster-daily
  namespace: condor-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  schedule: "0 0 1 * * *"
  backupOwnerReference: self
  cluster:
    name: condor02-postgres-cluster
  method: barmanObjectStore
  target: prefer-standby
